..  |ACC|           replace:: Austin Community College
..  _ACC:           http://www.austincc.edu/
..  |VL|            replace:: VisualLogic
..  _VL:            http://www.visuallogic.org
..  |VB|            replace:: VirtualBox
..  _VB:            https://www.virtualbox.org/
..  |WWW|           replace:: World-Wide-Web
..  |RST|           replace:: reStructuredText
..  _RST:           http://docutils.sourceforge.net/rst.html
..  |WE|            replace:: WIndows Explorer
..  |pylit| replace::   PyLiT
..  |SDL|           replace:: Simple DirectMedia Layer

..  _`Donald Knuth`:	https://en.wikipedia.org/wiki/Donald_Knuth
..  _Knuth:         https://en.wikipedia.org/wiki/Donald_Knuth
..  _reStructuredText: //http://docutils.sourceforge.net/rst.html
..  _`Literate Programming`: https://en.wikipedia.org/wiki/Literate_programming

..  _AgnerFog:      http://www.agner.org/optimize/
..  _Ansible:       https://www.ansible.com/
..  _Atmel:         http://www.microchip.com/
..  _Arduino:       https://www.arduino.cc/
..  _Beamer:        http://tug.ctan.org/macros/latex/contrib/beamer/README.md
..  _Docker:        https://www.docker.com/
..  _Etcher:        https://etcher.io/
..  _JSON:          https://www.json.org/
..  _MacTex:        http://www.tug.org/mactex/
..   _Microchip:     http://www.microchip.com/
..  _catch.hpp:     https://github.com/catchorg/Catch2
..  _Donald Knuth:  https://en.wikipedia.org/wiki/Donald_Knuth
..  _Knuth:         https://en.wikipedia.org/wiki/Donald_Knuth
..  _George Boole:  https://en.wikipedia.org/wiki/George_Boole
..  _Git:           https://git-scm.com/
..  _GitHub:        https://github.com/
..  _GitLab:        https://about.gitlab.com/
..  _Go:            https://golang.org/
..  _Google:        https://www.google.com/
..  _Gravatar:      https://en.gravatar.com/
..  _GTKwave:       http://gtkwave.sourceforge.net/
..  _Gvim:          https://www.vim.org/
..  _Homebrew:      https://brew.sh/
..  _Icarus Verilog: http://iverilog.icarus.com/
..  Verilog:        http://www.verilog.com/
..  _LaTeX:         https://www.latex-project.org/
..  _Linus Torvalds:    https://en.wikipedia.org/wiki/Linus_Torvalds
..  _Literate Programming:  https://en.wikipedia.org/wiki/Literate_programming
..  _Linux:         https://www.linux.org/
..  _Make:          https://www.gnu.org/software/make/manual/
..  _MARSSx86:        http://marss86.org/~marss86/index.php/Home
..	_mingw-w64:	https://mingw-w64.org/doku.php
..  _Nasm:          http://nasm.us/
..  _Parallels:     https://www.parallels.com/
..  _Parallax:      https://www.parallax.com
..  _PL0:           https://en.wikipedia.org/wiki/PL/0
..  _ProGit:        https://git-scm.com/book/en/v2
..  _Python:        https://www.python.org/
..  _RaspberryPi:   https://www.raspberrypi.org/
..  _simavr:	    https://github.com/buserror/simavr
..  _SparkFun:      https://www.sparkfun.com/
..  _Sphinx:        http://sphinx-doc.org/
..  _StackOverflow: https://stackoverflow.com/
..  _Tatsu:         https://pypi.python.org/pypi/tatsu
..  _Teensy2:       https://www.pjrc.com/store/teensy.html
..  _Teensy:        https://www.pjrc.com/store/teensy.html
..  _TeX:           https://www.tug.org/begin.html  
..  _TikZ:          https://sourceforge.net/projects/pgf/
..  _TikzBuilder:   https://github.com/rblack42/TikzBuilder/
..  _TravisCI:      https://travis-ci.org/ 
..  _Ubuntu:        http://www.ubuntu.com/
..  _Vagrant:       https://www.vagrantup.com/
..  _Verilog:       http://www.verilog.com/
..  _Vim:           http://www.vim.org/
..  _VMware:        https://www.vmware.com/
..  _VirtualBox:    https://www.virtualbox.org/
