Week 1
******

.. toctree::
   :maxdepth: 1

   /lectures/01-Course-Introduction/01-introduction
   /lectures/01-Course-Introduction/02-history-lesson
   /lectures/01-Course-Introduction/03-virtual-machine
   /lectures/01-Course-Introduction/04-getting-started
   /lectures/01-Course-Introduction/05-assignment-policies

Assignments
===========

.. toctree::
   :maxdepth: 1

   /assignments/homework/hw1-github/index

Week 2
******

.. toctree::
   :maxdepth: 1

   /lectures/03-Basic-Concepts/01-digital-components
   /lectures/03-Basic-Concepts/02-wires-and-pins
   /lectures/03-Basic-Concepts/03-electricity
   /lectures/03-Basic-Concepts/04-lets-dance
   /lectures/02-Development-Techniques/01-shell-basics
   /lectures/02-Development-Techniques/02-github-classroom
   /lectures/02-Development-Techniques/03-project-folders

Assignments
===========

.. toctree::
   :maxdepth: 1

   /assignments/homework/hw2-hello-project/index
   /assignments/labs/lab1-dancing/index

Week 3
******

   /lectures/

Assignments
===========

.. toctree::
   :maxdepth: 1


Week 4
******

   /lectures/

Assignments
===========

.. toctree::
   :maxdepth: 1


Week 5
******

   /lectures/

Assignments
===========

.. toctree::
   :maxdepth: 1


Week 6
******

   /lectures/

Assignments
===========

.. toctree::
   :maxdepth: 1


Week 7
******

   /lectures/

Assignments
===========

.. toctree::
   :maxdepth: 1


Week 8
******

   /lectures/

Assignments
===========

.. toctree::
   :maxdepth: 1


Week 8
******

   /lectures/

Assignments
===========

.. toctree::
   :maxdepth: 1


Week 9
******

   /lectures/

Assignments
===========

.. toctree::
   :maxdepth: 1


Week 10
*******

   /lectures/

Assignments
===========

.. toctree::
   :maxdepth: 1


Week 11
*******

   /lectures/

Assignments
===========

.. toctree::
   :maxdepth: 1


Week 12
*******

   /lectures/

Assignments
===========

.. toctree::
   :maxdepth: 1


Week 13
*******

   /lectures/

Assignments
===========

.. toctree::
   :maxdepth: 1


Week 14
*******

   /lectures/

Assignments
===========

.. toctree::
   :maxdepth: 1


Week 15
*******

   /lectures/

Assignments
===========

.. toctree::
   :maxdepth: 1


Week 16
*******

   /lectures/

Assignments
===========

.. toctree::
   :maxdepth: 1


